crab submit -c DoubleMuon_Run2018A_cfg.py  &
crab submit -c DoubleMuon_Run2018B_cfg.py  &
crab submit -c DoubleMuon_Run2018C_cfg.py  &
crab submit -c DoubleMuon_Run2018D_cfg.py  &
crab submit -c EGamma_Run2018A_cfg.py  &
crab submit -c EGamma_Run2018B_cfg.py  &
crab submit -c EGamma_Run2018C_cfg.py  &
crab submit -c EGamma_Run2018D_cfg.py  &
crab submit -c MuonEG_Run2018A_cfg.py  &
crab submit -c MuonEG_Run2018B_cfg.py  &
crab submit -c MuonEG_Run2018C_cfg.py  &
crab submit -c MuonEG_Run2018D_cfg.py  &
crab submit -c SingleMuon_Run2018A_cfg.py  &
crab submit -c SingleMuon_Run2018B_cfg.py  &
crab submit -c SingleMuon_Run2018C_cfg.py  &
crab submit -c SingleMuon_Run2018D_cfg.py  &
